import Background from "./components/Background";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-5xl h-screen mx-auto flex flex-col relative z-10 overflow-hidden pb-4">
          <Header />
          {children}
        </main>
        <Background />
      </body>
    </html>
  );
}
